Scripts finally fixed

diff --git a/command/run b/command/run
--- a/command/run
+++ b/command/run
@@ -1,10 +1,6 @@
 #!/bin/bash -e
 
-script_dir=$(dirname "$0")
-
-input_file=input
-part=1
-UPDATE_PART='part=$([[ -f part-2$($script_dir/lang -e $language) ]] && echo 2 || echo 1)'
+script_dir=$(dirname "$BASH_SOURCE")
 
 print_help() {
     echo 'usage: aoc run [-dh] [-p 1|2] [-l LANGUAGE]'
@@ -16,51 +12,57 @@ print_help() {
 }
 
 load_options() {
-    part_set=0
-
     while getopts :dhl:p: flag; do
         case "${flag}" in
-            d) input_file='input.debug';;
-            l) language=$OPTARG; [[ $part_set == 0 ]] && eval $UPDATE_PART || true;;
-            p) part=$OPTARG; part_set=1;;
-            h) print_help; exit 0;;
-            *) print_help; exit 1;;
+            d)  input_file='input.debug'
+                ;;
+            l)  language=$OPTARG
+                ;;
+            p)  part=$OPTARG
+                ;;
+            h)  print_help
+                exit 0
+                ;;
+            *)  print_help >&2
+                exit 1
+                ;;
         esac
     done
 }
 
+input_file=input
+
 load_options "$@"
 
 # Checks wether a solution script actually exist
-if ! compgen -G "part-*.*" > /dev/null; then
-    echo Error: no solution found to run
+if ! ls part-[12].* &> /dev/null; then
+    echo Error: no solution found >&2
     exit 1
 fi
 
-# Retrieves the current selected language
-language=$($script_dir/lang)
+# Retrieves the current selected language (if not already specified)
+[[ -n $language ]] || language=$($script_dir/lang -c)
+extension=$($script_dir/lang -e $language)
 
-[[ $(bc -e "$(echo "$language" | wc -l) > 1") == 1 ]] && [[ $(echo "$language" | grep default) ]] && language=$(echo "$language" | grep default | sed 's/ (default)//')
-
-[[ $(bc -e "$(echo "$language" | wc -l) > 1") == 0 ]] && eval $UPDATE_PART
-
-if [[ $(bc -e "$(echo "$language" | wc -l) > 1") == 1 ]]; then
-    echo Error: multiple languages detected > &2
-    echo '' > &2
-    echo Run your solution with \'run -l LANGUAGE\' > &2
-    echo Or set a default language for this day with \'lang -s LANGUAGE\' > &2
+language_script=$script_dir/../run-language/$language
+if [[ ! -f $language_script ]]; then
+    echo "Error: '$language' is not supported yet" >&2
     exit 1
 fi
 
-# Runs the solution in the selected language and copies the result on the system clipboard ready to be pasted on adventofcode.com
-if [[ -f $script_dir/../run-language/$language ]]
-then
-    # Running the script with the input as stdin, passing as arguments the part to run and the input file
-    $script_dir/../run-language/$language $part $input_file < $input_file | pbcopy
-else
-    echo Error: the selected language has not yet been configured > &2
-    exit 1
+if [[ -z "$part" ]]; then
+    if [[ -f part-2$extension ]]; then
+        part=2
+    elif [[ -f part-1$extension ]]; then
+        part=1
+    else
+        echo "Error: no solution, written in '$language', found" >&2
+        exit 1
+    fi
 fi
+
+# Run the script with the input as stdin, passing as arguments the part to run and the input file
+$language_script $part $input_file < $input_file | pbcopy
 
 # Outputs the result, for debugging purposes
 pbpaste
